export default {
  CONNECTION: "connection",
  DISCONNECT: "disconnect",
  EXPIRED: "expired",
  NEW_USER: "new user",
  USER_OUT: "user out",
  USER_REGISTER: "user register",
  GET_USERS: "get users",
  GET_GROUPS: "get groups",
  USER_LOGGED: "user logged",
  SEND_MSG: "send msg",
  SEND_GROUP_MSG: "send group msg",
  GET_MSG: "get msg",
  GET_GROUP_MSG: "get group msg",
  LISTEN_GROUP_MSG: "listen group msg",
  GET_HISTORY: "get history",
  GET_GROUP_HISTORY: "get group history",
  GET_GROUP_HISTORY_ANON: "get group history anon",
  USER_LOGGED_WILD_SUB: "user logged wild sub",
  SEND_USERS: "send users",
  LOGGED_NEW_USER: "logged new user",
  REFRESH: "refresh",
  READ_MSG: "read msg",
  READ_GROUP_MSG: "read group msg",
  DELETE_GROUP_MSG: "delete group msg",
  BAN_GROUP_USER: "ban group user",
  UNBAN_GROUP_USER: "unban group user",
  UNREAD: "unread",
  FORBIDDEN: "forbidden",
  ALL_REFRESH: "allRefresh",
  USER_LOGGED_AS_ANNON: "user logged as annon",
  UPDATE_FAV_GROUPS: "update fav groups",
  GET_FAV_GROUPS: "get fav groups",
}